version: '3'
services:
  falafel:
    build: .
    image: 278380418400.dkr.ecr.us-east-2.amazonaws.com/falafel:latest
    tty: true
    stdin_open: true
    environment:
      NODE_ENV: production
    ports:
      - '80:80'
    volumes:
      - ./data:/usr/src/falafel/data
